# Generated by Django 3.1.4 on 2020-12-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome')),
                ('proteina', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Proteinas G:')),
                ('carbo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Carboidratos  G:')),
                ('caloria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Calorias  G:')),
                ('sodio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sódio G:')),
                ('vibra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fibras G:')),
                ('polisaturado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Polisaturado G:')),
                ('poliInsaturado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Poli-Insaturado G:')),
                ('monosaturado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monosaturado G:')),
                ('monoinsaturado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mono-Insaturado G:')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
            },
        ),
    ]
