# Generated by Django 3.1.4 on 2020-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='monoinsaturado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Mono-Insaturado G:'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='monosaturado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Monosaturado G:'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='poliInsaturado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Poli-Insaturado G:'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='polisaturado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Polisaturado G:'),
        ),
    ]
