# Generated by Django 3.1.4 on 2020-12-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_auto_20201214_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimento',
            old_name='vibra',
            new_name='fibra',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='caloria',
        ),
        migrations.AddField(
            model_name='alimento',
            name='gordura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Gordura  G:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alimento',
            name='monoinsaturado',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Mono-Insaturado G:'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='monosaturado',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Monosaturado G:'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='poliInsaturado',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Poli-Insaturado G:'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='polisaturado',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Polisaturado G:'),
        ),
    ]
