# Generated by Django 3.1.4 on 2020-12-15 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receitas', '0002_auto_20201215_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
